/*
 * GPIO_Cfg.c
 *
 *  Created on: Oct 28, 2018
 *      Author: Mati
 */
#include "Std_Types.h"
#include "GPIO_Cfg.h"
#include "gpio.h"

void InitGPIO(void)
{
  uint16 i;
  for (i = 0; i < 512; i++)
  {
    gpio_config(i, 0);
  }
  gpio_config(PAD_SPARKDUR, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_NOMI, GPIO_IO_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_MAXI, GPIO_IO_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_FUEL1, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_FUEL2, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_FUEL3, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_FUEL4, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_IGN1, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_IGN2, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_IGN3, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_IGN4, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_OUTEN, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_CS_810, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_CS_800, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_CRANK, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAM, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
#ifdef DEBUG
  gpio_config(PAD_CRANK_TG, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAM_TG, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
#else
  gpio_config(PAD_CRANK_TG, GPIO_IO_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAM_TG, GPIO_IO_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
#endif
  gpio_config(PAD_IND1, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_IND2, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_IND3, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_IND4, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_SQWE, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_ESCI_A_TX, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_ESCI_A_RX, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAN_A_TX, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAN_A_RX, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAN_C_TX, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_CAN_C_RX, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_MISO_B, GPIO_PRIMARY_FUNCTION | GPIO_INPUT_BUFFER_ENABLE);
  gpio_config(PAD_MOSI_B, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_SCLK_B, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM_MOS1, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM_MOS2, GPIO_PRIMARY_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM_MOS3, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM12, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM34, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM56, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_PWM78, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_VSNS_EN, GPIO_IO_FUNCTION | GPIO_OUTPUT_BUFFER_ENABLE);
  gpio_config(PAD_UART_TX, GPIO_PRIMARY_FUNCTION + GPIO_OUTPUT_MODE);
  gpio_config(PAD_UART_RX, GPIO_PRIMARY_FUNCTION + GPIO_INPUT_MODE);
}