
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT!
*
* COPYRIGHT (c) Freescale 2004-2014, All Rights Reserved
*
* FILE NAME: etpu_fuel.h
* ARCHITECTURE: eTPU2
*
* This file was generated by: etpuc_fuel.c on Apr  9 2014 , 09:29:34
*
* This file provides an interface between eTPU code and CPU
* code. All references to the eTPU function should be made with
* information in this file. This allows only symbolic
* information to be referenced which allows the eTPU code to be
* optimized without effecting the CPU code.
*****************************************************************/
#ifndef _ETPU_FUEL_AUTO_H_
#define _ETPU_FUEL_AUTO_H_

/* Function Configuration Information */
#define FS_ETPU_FUEL_FUNCTION_NUMBER 3
#define FS_ETPU_FUEL_TABLE_SELECT 1
#define FS_ETPU_FUEL_NUM_PARMS 0x40


/* Host Service Request Definitions */
#define FS_ETPU_FUEL_HSR_INIT 7
#define FS_ETPU_FUEL_HSR_STOP 5
#define FS_ETPU_FUEL_HSR_UPDATE 3

/* Function Mode Bit Definitions */
#define FS_ETPU_FUEL_FM0_ACTIVE_LOW 0
#define FS_ETPU_FUEL_FM0_ACTIVE_HIGH 1

/* Parameter Definitions */
#define FS_ETPU_FUEL_OFFSET_ERROR  0x4
#define FS_ETPU_FUEL_OFFSET_TDC_ANGLE  0x1
#define FS_ETPU_FUEL_OFFSET_TDC_ANGLE_ACTUAL  0x5
#define FS_ETPU_FUEL_OFFSET_ANGLE_NORMAL_END  0x9
#define FS_ETPU_FUEL_OFFSET_ANGLE_STOP  0xd
#define FS_ETPU_FUEL_OFFSET_ANGLE_OFFSET_RECALC  0x11
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME  0x15
#define FS_ETPU_FUEL_OFFSET_COMPENSATION_TIME  0x19
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME_MINIMUM  0x1d
#define FS_ETPU_FUEL_OFFSET_OFF_TIME_MINIMUM  0x21
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME_APPLIED  0x25
#define FS_ETPU_FUEL_OFFSET_INJECTION_TIME_APPLIED_CPU 0x29
#define FS_ETPU_FUEL_OFFSET_INJECTION_START_ANGLE  0x2d
#define FS_ETPU_FUEL_OFFSET_INJECTION_START_ANGLE_CPU  0x31
#define FS_ETPU_FUEL_OFFSET_PULSE_START_TIME  0x35
#define FS_ETPU_FUEL_OFFSET_PULSE_END_TIME  0x39
#define FS_ETPU_FUEL_OFFSET_GENERATION_DISABLE  0x0

/* Error Flags Definitions */
#define FS_ETPU_FUEL_ERROR_STOP_ANGLE_APPLIED 0x01
#define FS_ETPU_FUEL_ERROR_MINIMUM_INJ_TIME_APPLIED 0x02

/* Generation Disable Definitions */
#define FS_ETPU_FUEL_GENERATION_ALLOWED 0
#define FS_ETPU_FUEL_GENERATION_DISABLED 1

#endif
