
/**************************************************************** 
* WARNING: This file is automatically generated. DO NOT EDIT IT!
*
* COPYRIGHT (c) Freescale 2004-2014, All Rights Reserved
*
* FILE NAME: etpu_tg_auto.h
* ARCHITECTURE: eTPU2
*
* This file was generated by: etpuc_tg.c on Apr  9 2014 , 09:29:41
*
* This file provides an interface between eTPU code and CPU
* code. All references to the eTPU function should be made with
* information in this file. This allows only symbolic
* information to be referenced which allows the eTPU code to be
* optimized without effecting the CPU code.
*****************************************************************/
#ifndef _ETPU_TG_AUTO_H_
#define _ETPU_TG_AUTO_H_

/* Function Configuration Information */
#define FS_ETPU_TG_FUNCTION_NUMBER 7
#define FS_ETPU_TG_TABLE_SELECT 1
#define FS_ETPU_TG_NUM_PARMS 0x20


/* Host Service Request Definitions */
#define FS_ETPU_TG_HSR_INIT 7

/* Function Mode Bit Definitions */
#define FS_ETPU_TG_FM0_POLARITY_LOW 0
#define FS_ETPU_TG_FM0_POLARITY_HIGH 1
#define FS_ETPU_TG_FM1_CRANK (0 << 1)
#define FS_ETPU_TG_FM1_CAM (1 << 1)

/* Parameter Definitions */
#define FS_ETPU_TG_OFFSET_TOOTH_TCR1_TIME  0x1
#define FS_ETPU_TG_OFFSET_TOOTH_PERIOD_ACTUAL 0x5
#define FS_ETPU_TG_OFFSET_TOOTH_PERIOD_TARGET 0x9
#define FS_ETPU_TG_OFFSET_ACCEL_RATIO  0xd
#define FS_ETPU_TG_OFFSET_P_CAM_TOOTH_FIRST  0x11
#define FS_ETPU_TG_OFFSET_P_CAM_TOOTH  0x15
#define FS_ETPU_TG_OFFSET_TEETH_TILL_GAP  0x0
#define FS_ETPU_TG_OFFSET_TEETH_IN_GAP  0x4
#define FS_ETPU_TG_OFFSET_TEETH_PER_CYCLE  0x8
#define FS_ETPU_TG_OFFSET_TOOTH_COUNTER_GAP  0xc
#define FS_ETPU_TG_OFFSET_TOOTH_COUNTER_CYCLE 0x10
#define FS_ETPU_TG_OFFSET_CAM_CHAN  0x14
#define FS_ETPU_TG_OFFSET_GENERATION_DISABLE  0x18

/* Generation Disable Definitions */
#define FS_ETPU_TG_GENERATION_ALLOWED 0
#define FS_ETPU_TG_GENERATION_DISABLED 1

#endif
